### ISSUE TITLE
Ostim equivalent to sexlabs HasPlayer and HasActor.

### ISSUE THREAD

**Issue by Osmosis-Wrench** [Sairion350/OStim#15]
Sexlab allows you to query a thread and return if the player or a specific actorref is in that thread. If you want to do the same thing in Ostim you need to do something ugly like:
`if (Ostim.GetDomActor() == PlayerRef || Ostim.GetSubActor() == PlayerRef || Ostim.GetThirdActor() == PlayerRef)`
My understanding is that we currently cache the actors of the most recent ostim scene until a new one starts, so it shouldn't be an issue to return those even if a scene isn't currently running.
Something you could call from OsexIntergrationMain would be ideal.
`if (Ostim.HasPlayer() || Ostim.HasActor(Follower.GetActorRef())`
Would be best probably?

**Comment by Sairion350** [comment]
Ostim.isactoractive() already exists
