### ISSUE TITLE
No graceful detection of user actor rearrange events

### ISSUE THREAD

**Issue by Sairion350** [Sairion350/OStim#23]
Currently there is no easy way to do this. As a consequence, scaling is not reapplied correctly on flip.

**Comment by kannonfodder** [comment]
So i found a thing in the swf...
We can listen for 0SAO+password+_ActraSync when actors are rearranged.
![image](https://user-images.githubusercontent.com/7817876/125680482-6abc49ac-d498-43b4-913c-9af9fa189859.png)
I'm not sure how/what we want to do with this, but it looks like it passes out the following data as the string Arg:
NoOfActors,Actor[0].id,Actor[1].id (etc)
![20210714202755_1](https://user-images.githubusercontent.com/7817876/125681440-c0094606-94a4-4cf2-acc8-2914643327af.jpg)
![20210714202809_1](https://user-images.githubusercontent.com/7817876/125681444-3d9a5e95-4e91-43ef-ae9f-5f8044af5e25.jpg)

**Comment by Sairion350** [comment]
It's been a while since i've looked at this issue but i'll note this down, might be a good find

**Comment by Sairion350** [comment]
Fixed by kannon
