### ISSUE TITLE
Improved Camera ini file and PrivateProfile Redirector

### ISSUE THREAD

**Issue by inire** [Sairion350/OStim#34]
Hello,

There is a problem with the Improved Camera ini file included in the OStim optional page, where the head part appears to "lag behind" the body in the first person, and some scripted camera scenes (ex. Falskaar ending is HEAVILY third-person scripted) are also broken because of this.

Here is the PrivateProfile Redirector mod

https://www.nexusmods.com/skyrimspecialedition/mods/18860

The mod loads all INI files into a cache, which speeds up response time for fetching these values.

Here is a link to an issue that I made on that mod for the improved camera ini

https://forums.nexusmods.com/index.php?/topic/6852592-privateprofileredirector-faster-game-start-ini-file-cacher/page-46#entry95758983

It appears that there are a few problems here.

1. The OStim Improved Camera ini file has a copy/paste issue lines 308-311. From that thread, "In the original file, on lines 308-311 there are options�fScriptedCameraPosX,�fScriptedCameraPosY,�fScriptedCameraPosZ but in the OStim file in the same place, they're�fCameraPosX,�fCameraPosY,�fCameraPosZ (see, no "Scripted" part) which matches a different set of options earlier on lines 274-276. Since there is only one section in the INI file (Main, one option overwrites the other. I don't know how this could affect things, but it could�be the reason. Try to renamed those options in the OStim file by adding "Scripted" to the name (e. g.�fCameraPosX ->�fScriptedCameraPosX and so on). "

2. From Kerber100 on the PPR page, "So it seems that WinAPI (which is what the original game uses) and the INI parser I use in PPR employ different strategies when multiple identical options are present in the same section. I'll inform the author of that modified INI file. "

To fix this, I have edited the ini file, per Kerber100's instructions, and tested successfully on both a utility Wabbajack (SMEFT with just Improved Camera and PPR) and on Licentia 9 (beta version).  The attached file fixes this issue, and has the corrected scripted head positions, which fixes some issues I was also seeing while in Falsaar (using Licentia) in the scripted ending scenes.

[ImprovedCamera.zip](https://github.com/Sairion350/OStim/files/6710209/ImprovedCamera.zip)

**Comment by inire** [comment]
Created this mod to test with Wabbajack
https://www.nexusmods.com/skyrimspecialedition/mods/51579

Will drop it like it's hot if needed.

**Comment by Sairion350** [comment]
Tested it and seems like everything you're saying checks out. i can push this has ini version 1.3 in the next release if you want

**Comment by inire** [comment]
absolutely. All yours. I don't really want to run a mod if I can avoid it lol.

When yours is up I'll put mine into hidden.
