### ISSUE TITLE
If Scene is re-arragned then redress uses the wrong clothes

### ISSUE THREAD

**Issue by kannonfodder** [Sairion350/OStim#41]
Because we're changing the Dom/Sub/Third actors to match the position in the OSA scene, the calls to GetDomActor etc in OUndress no longer point to the correct actors
We could track the actor refs in OUndress on scene start and on third actor join instead of calling into ostim every time. If we go this route I think we'll need to make a call to GetActors to determine which actor has left the threesome (instead of using the current var) because the Third actor could be switched around and that ref will no longer be accurate

**Comment by Sairion350** [comment]
Sounds good

**Comment by kannonfodder** [comment]
Because of the naming of the properties I think I'm actually going to do re-arrange tracking instead. DomEquipmentForms etc should always point at the clothes of the Dom

**Comment by Sairion350** [comment]
I think this is fixed now? Let me know if not
