### ISSUE TITLE
SMP hair blocked while scene in progress

### ISSUE THREAD

**Issue by Alakelele** [Sairion350/OStim#43]
Hello all, thanks for the cool project, SMP hair seems to have problems with the animations, as soon as the body moves, the air gets stuck in air and stays there, i tried to disable scaling and it seemed to work for one animation cycle but it came back after, strange.
Picture attached
![ScreenShot10](https://user-images.githubusercontent.com/43206650/127752540-5b39ff1d-29cb-4d8d-93b6-7d75b845e163.png)

**Comment by Sairion350** [comment]
SMP hair has been broken with OSA for as long as I know. Nobody has discovered any fix yet, might not be fixable due to the nature of how SMP works? Closing in a bit unless someone has some suggestions for fixing

**Comment by Osmosis-Wrench** [comment]
Is it broken in only in freecam? Or is it broken no matter what?
My understanding is hair is essentially just another armor, so it could be ninode shit again.
Are SMP armours also broken in in scenes?

**Comment by Alakelele** [comment]
![ScreenShot11](https://user-images.githubusercontent.com/43206650/127765610-aadb1a91-af04-4a48-9b29-15730081b03f.png)
Well, it seems to work sometimes so there is possible fix, if we try with different setups we might isolate the malfunction, why would you want to close this issue ?

**Comment by Sairion350** [comment]
I've already spent a week trying to fixt it back in may, concluded that fixing require modding HDT-SMP. Need a third party to bring more info on a possible fix or I have to mark it as unfixable

**Comment by Alakelele** [comment]
Do you want us to really look into it ? That's what the community is for, so far I have a couple of saves where there's no problem, we could extract the log and settings of the right situation and compare it to a faulty one.

**Comment by Sairion350** [comment]
Closing for now since it's a compatibility issue, may reopen at a later date when ready to fix incompatibilities
