### ISSUE TITLE
Strip() failure

### ISSUE THREAD

**Issue by Sairion350** [Sairion350/OStim#50]
Sometimes (~20% of the time) when I start a new game (I always start a new game when I test something), strip() will just fail and the actors will not get naked. It even happens if I call strip() manually outside of a scene. I have not seen anyone else report this so I'm not exactly sure what's going on.

**Comment by Sairion350** [comment]
Turns out an MCM file with only the slots "49" was sitting in my game folder and this was being autoloaded.

May want a reminder to periodically clear these old mcm saves every few versions

**Comment by Osmosis-Wrench** [comment]
@Sairion350 I can start storing the ostim version in the save file, and some sort of comparison could be done to check if it's too old.

**Comment by Sairion350** [comment]
Sure
