### ISSUE TITLE
Hearthfire multiple adoptions mod incombatilbity

### ISSUE THREAD

**Issue by Sairion350** [Sairion350/OStim#56]
https://www.nexusmods.com/skyrimspecialedition/mods/3862

Seems to break some bed searching: https://discord.com/channels/771971253199699988/833189051200045076/884184785310875689

**Comment by Osmosis-Wrench** [comment]
![image](https://user-images.githubusercontent.com/77623077/132165363-8d8073c4-8308-498f-b2ec-e2c95e7b5331.png)
Looks like it edits the furniture record for NobleBedDouble01, that could potentially be the issue.

**Comment by Sairion350** [comment]
Removing the RaceToScale keyword does it. Not sure what to do about situations like this

**Comment by Osmosis-Wrench** [comment]
apparently po3 extender has functions to add or remove keywords at runtime, though I'm unsure if they'll work with furniture though.

**Comment by Sairion350** [comment]
I think i'll close this for now, if beds get revisited it will be archived as a reference
