### ISSUE TITLE
Alternative causes for this error message.

### ISSUE THREAD

**Issue by Osmosis-Wrench** [Sairion350/OStim#7]
https://github.com/Sairion350/OStim/blob/87429259dbfcbcf55fb471fcb095c5f5b76dd73b/scripts/source/OsexIntegrationMain.psc#L2650

This can also be thrown if OSA fails to load, for example is SkyUI is not installed. Perhaps the response should be expanded to include those as potential causes. Alternatively, a seperate test to check that OSA / skyui is loaded at all could be implemented.

**Comment by Sairion350** [comment]
Just did this a few minutes ago, we're good now
